### ISSUE TITLE
error cactching

### ISSUE THREAD

**Issue by chanikyathegodg** [Aarya5122/Golify#1]
in error catch use 
{  success: false,
            messageSrc: "Error in create todo controller",
            error}

{  success: false,
            messageSrc: "Error in create todo controller",
            error:error.message}

**Comment by Aarya5122** [comment]
Thanks, @chanikyathegodg  for reaching out. Yeah, sure I will do that once I add user authentication. As the project is in the developing phase I am logging the whole error. Thanks for your insight I will surely update it in the production phase.

**Comment by chanikyathegodg** [comment]
Can you contact me on  ihave doubts regarding the todo Websie
thanks for reply

**Comment by Aarya5122** [comment]
[Instagram](https://www.instagram.com/aarya_5122/)
[LinkedIn](https://www.linkedin.com/in/aarya5122/)
You can reach me out here
